apiVersion: v1
kind: Service
metadata:
  name: java-confluence-nodeport-svc
spec:
  type: NodePort
  ports:
   - port: 8090
     protocol: TCP
     targetPort: 8090
     name: java-confluence-nodeport-svc1
     nodePort: 31791
   - port: 8091
     protocol: TCP
     targetPort: 8091
     name: java-confluence-nodeport-svc2
     nodePort: 31792
  selector:
    #app: mysql-0
     statefulset.kubernetes.io/pod-name: java-confluence-wiki
