apiVersion: v1
kind: Service
metadata:
  name: java-confluence-wiki-svc
  namespace: default
spec:
  ports:
  - name: port
    port: 8080
    protocol: TCP
    targetPort: 7789
  selector:
    app: java-confluence-wiki
  #type: NodePort
