apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-run-data-pv-volume
spec:
  storageClassName: confluence-run-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/kubernetes/volums/confluence-run-data
    server: 10.25.96.30
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-sys-data-pv-volume
spec:
  storageClassName: confluence-sys-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/kubernetes/volums/confluence-sys-data
    server: 10.25.96.30
    readOnly: false
