apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-pv-volume
spec:
  storageClassName: confluence-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/kubernetes/volums/confluence-data/
    server: 10.25.96.30
    readOnly: false
