apiVersion: v1
kind: Service
metadata:
  name: java-confluence-wiki-svc
  namespace: default
spec:
  ports:
  - name: confluenceport8090
    port: 8090
    protocol: TCP
    targetPort: 8090
  ports:
  - name: confluenceport8091
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: java-confluence-wiki
  #type: NodePort
