apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: java-confluence-wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-confluence-wiki
  serviceName: java-confluence-wiki
  template:
    metadata:
      labels:
        app: java-confluence-wiki
    spec:
      containers:
      - name: java-confluence-wiki
        image: wolihi/java-confluence-wiki:v7.9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: confluence-data
          mountPath: /var/atlassian/confluence
          subPath: confluence-run-data
          mountPath: /opt/atlassian/confluence
  volumeClaimTemplates:
  - metadata:
      name: confluence-data
    spec:
      accessModes:
      - "ReadWriteMany"
      storageClassName: confluence-storage
      resources:
        requests:
          storage: 15Gi
