apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
spec:
  storageClassName: postgresql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
