apiVersion: apps/v1
kind: Deployment
metadata:
  name: pronsearch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pronsearch
  template:
    metadata:
      labels:
        app: pronsearch
    spec:
      containers:
      - name: pronsearch
        image: wolihi/pronsearch:v1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 7788
        env:
        - name: REVISION
          value: v1.5
        - name: db_username
          value: "root"
        - name: db_host
          value: "mysql-master-svc"
          #value: "mysql"
        - name: db_port
          value: "3306"
        - name: db_name
          value: "pronsearch"
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      #imagePullSecrets:
      #- name: wangdi-docker-password
