apiVersion: v1
kind: Service
metadata:
  name: pronsearch-svc
  namespace: default
spec:
  ports:
  - name: port
    port: 7788
    protocol: TCP
    targetPort: 7788
  selector:
    app: pronsearch
  #type: NodePort
