apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-pronsearch-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-pronsearch-web
  template:
    metadata:
      labels:
        app: flask-pronsearch-web
    spec:
      containers:
      - name: flask-pronsearch-web
        image: wolihi/flask-pronsearch-web:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7788
        env:
        - name: REVISION
          value: v1.0
        - name: db_username
          value: "root"
        - name: db_host
          value: "mysql"
          #value: "mysql"
        - name: db_port
          value: "3306"
        - name: db_name
          value: "flask-pronsearch-web"
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      #imagePullSecrets:
      #- name: wangdi-docker-password
