apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pv-volume
spec:
  storageClassName: jira-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/kubernetes/volums/jira-data/
    server: 10.25.96.30
