apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-jira-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-jira-office
  template:
    metadata:
      labels:
        app: java-jira-office
    spec:
      containers:
      - name: java-jira-office
        image: wolihi/java-jira-office:last
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: X_PROXY_SCHEME
          value: "https"
        - name: X_PROXY_SCHEME
          value: "443"
        - name: X_PROXY_NAME
          value: "jira.mouthmelt.com"
        - name: SETENV_JVM_MAXIMUM_MEMORY
          value: "2048"
        - name: SETENV_JVM_MINIMUM_MEMORY
          value: "1024"
        - name: JIRA_DATABASE_URL
          value: "mysql-master-svc"
        - name: JIRA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      #imagePullSecrets:
      #- name: wangdi-docker-password
        volumeMounts:
        - name: jira-data
          mountPath: /var/atlassian/
          subPath: jira-application-data
        - name: jira-data
          mountPath: /etc/mysql/conf.d
          subPath: jira-logs
  volumeClaimTemplates:
  - metadata:
      name: jira-data
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: jira-storage
      resources:
        requests:
          storage: 3Gi
