apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blogdemo-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-blogdemo-web
  template:
    metadata:
      labels:
        app: django-blogdemo-web
    spec:
      containers:
      - name: djangdjango-blogdemo-weboblog
        image: wolihi/django-blogdemo-web:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7790
        env:
        - name: REVISION
          value: v1.5
        - name: db_username
          value: "root"
        - name: db_host
          value: "mysql-master-svc"
          #value: "mysql"
        - name: db_port
          value: "3306"
        - name: db_name
          value: "django-blogdemo-web"
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      #imagePullSecrets:
      #- name: wangdi-docker-password
