apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-payment-data
spec:
  storageClassName: php-payment-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/kubernetes/volums/php-payment-data
    server: 10.25.96.30
    readOnly: false
