apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-payment-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-payment-office
  template:
    metadata:
      labels:
        app: php-payment-office
    spec:
      containers:
      - name: php-payment-office
        image: wolihi/php-payment-office:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7789
        env:
        - name: REVISION
          value: v1.0
        - name: db_username
          value: "root"
        - name: db_host
          value: "mysql-master-svc"
          #value: "mysql"
        - name: db_port
          value: "3306"
        - name: db_name
          value: "php-payment-office"
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      #imagePullSecrets:
      #- name: wangdi-docker-password
