apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-payment-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-payment-office
  template:
    metadata:
      labels:
        app: php-payment-office
    spec:
      containers:
      - name: php-payment-office
        #image: wolihi/php-payment-office:v7.3
        #image: wolihi/php-payment-office:v7.2
        #image: wolihi/php-payment-office:v1.2
        image: wolihi/php-payment-office:v1.3
        #image: php:7.2-fpm 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: payment-data
          mountPath: /usr/local/kubernetes/volumes/php-payment-data/
        # - name: config-volume
        #   mountPath: /opt/atlassian/confluence/conf/server.xml
        #   subPath: .xml
      volumes:
      - name: payment-data
        persistentVolumeClaim:
          claimName: php-payment-pvc
