apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-payment-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-payment-office
  template:
    metadata:
      labels:
        app: php-payment-office
    spec:
      containers:
      - name: php-payment-office
        image: wolihi/php-payment-office:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: payment-data
          mountPath: /usr/share/nginx/html
        # - name: config-volume
        #   mountPath: /opt/atlassian/confluence/conf/server.xml
        #   subPath: .xml
      volumes:
      - name: payment-data
        persistentVolumeClaim:
          claimName: php-payment-pvc
