apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-payment-pvc
spec:
  storageClassName: php-payment-storage
  accessModes:
  #需要使用和PV 一致的访问方式
  - ReadWriteOnce
  #按需分配资源
  resources:
    requests:
      storage: 2Gi
