apiVersion: v1
kind: Service
metadata:
  name: php-payment-office-svc
  namespace: default
spec:
  ports:
  - name: port
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: php-payment-office
