apiVersion: v1
kind: PersistentVolume
metadata:
  name: rancher-run-data-pv-volume
spec:
  storageClassName: rancher-run-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/kubernetes/volums/rancher-data
    server: 10.25.96.30
    readOnly: false
