apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-sgk-config
data:
  #这里是键值对
  mysqld.cnf: |-
    [client]
    port = 3306
    default_character_set = utf8
    [mysql]
    no-auto-rehash
    [mysqld]
    skip-host-cache
    skip-name-resolve
    default-authentication-plugin = mysql_native_password
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
    explicit_defaults_for_timestamp = true
    lower_case_table_names = 1
    innodb_force_recovery = 1
    sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: default 
  name: mysql-sgk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-sgk
  template:
    metadata:
      namespace: default
      name: mysql-sgk
      labels:
        app: mysql-sgk
    spec:
      containers:
        - name: mysql-sgk
          image: mysql:5.7
          #只有镜像不存在时，才会进行镜像拉取
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 3306
          #同 Docker 配置中的 environment
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "Root!!2019"
          #容器中的挂载目录
          volumeMounts:
           - name: nfs-vol-mysql
             mountPath: /var/lib/mysql
           - name: timezone
             mountPath: /etc/localtime
           - name: cm-vol-sgk
             mountPath: /etc/mysql/conf.d
      volumes:
        #将ConfigMap中的内容以文件形式挂载近数据卷
        - name: cm-vol-sgk
          configMap:
            name: mysql-sgk-config
            items:
              #ConfigMap中的Key
              - key: mysqld.cnf
              #ConfigMap key匹配的Value 写入名位mysqld.cnf的文件中
                path: mysqld.cnf
        #挂载到数据卷
        - name: nfs-vol-mysql
          persistentVolumeClaim:
            claimName: nfs-pvc-mysql-sgk
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-sgk
spec:
  type: NodePort
  ports:
   - port: 3306
     protocol: TCP
     targetPort: 3306
     name: mysql-svc
     nodePort: 31308
  selector:
    app: mysql-sgk
