apiVersion: v1
kind: Service
metadata:
  name: mysql-master-svc
spec:
  type: NodePort
  ports:
   - port: 3306
     protocol: TCP
     targetPort: 3306
     name: mysql-svc
     nodePort: 31789
  selector:
    #app: mysql-0 
     statefulset.kubernetes.io/pod-name: mysql-0
