apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume3
spec:
  storageClassName: mysql-storage 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/kubernetes/volums/mysql-data/mysql3
    server: 10.25.96.30
