apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [client]
    default-character-set=utf8mb4
    [mysqld]
    #log-bin
    log-bin=mysqllog
    skip-name-resolve
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    [mysql]
    default-character-set=utf8mb4
    innodb_log_file_size = 256M
    max_allowed_packet = 128M
  slave.cnf: |
    # Apply this config only on slaves.
    [client]
    default-character-set=utf8mb4
    [mysqld]
    #super-read-only
    super-read-only
    skip-name-resolve
    log-bin=mysql-bin
    replicate-ignore-db=mysql
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    [mysql]
    default-character-set=utf8mb4
    innodb_log_file_size = 256M
    max_allowed_packet = 128M
