apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis-cluster-master
  name: redis-cluster-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cluster-master
  #所属服务的DNS域名
  serviceName: "redis-cluster-master"
  template:
    metadata:
      labels:
        app: redis-cluster-master
    spec:
      containers:
      - name: redis-cluster-master
        args:
          - -c
          - cp /mnt/redis-master.conf /data/ ; redis-server /data/redis-master.conf
        command:
          - bash
        image: "redis:3.2.8"
        imagePullPolicy: ifNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
            - name: redis-master-port
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
        volumeMounts:
          - mountPath: /mnt/
            readOnly: false
            name: redis-config-volume
          - mountPath: "/data"
            name: "redis-master-storage"
            readOnly: false
      volumes:
      - name: "redis-config-volume"
        configMap:
          name: "redis-cluster-conf"
          items:
            - key: "redis-master.conf"
              path: "redis-master.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-master-storage
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "redis-storage"
      resources:
        requests:
          storage: 3Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster-slave
  labels:
    app: redis-cluster-slave
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-cluster-slave
  #所属服务的DNS域名
  serviceName: "redis-cluster-salve"
  template:
    metadata:
      labels:
        app: redis-cluster-salve
    spec:
      containers:
      - name: redis-cluster-salve
        args:
          - -c
          - cp /mnt/redis-slave.conf /data/ ; redis-server /data/redis-slave.conf
        command:
          - bash
        image: "redis:3.2.8"
        imagePullPolicy: ifNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
            - name: redis-slave-port
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
        volumeMounts:
          - mountPath: /mnt/
            readOnly: false
            name: redis-config-volume
          - mountPath: "/data"
            name: "redis-slave-storage"
            readOnly: false
      volumes:
      - name: "redis-config-volume"
        configMap:
          name: "redis-cluster-config"
          items:
            - key: "redis-slave.conf"
              path: "redis-slave.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-slave-storage
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "redis-storage"
      resources:
        requests:
          storage: 3Gi
