apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume1
spec:
  storageClassName: redis-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/kubernetes/volums/redis-data/redis1
    server: 10.25.96.30
