apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster-slave
  labels:
    app: redis-cluster-slave
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-cluster-slave
  #所属服务的DNS域名
  serviceName: "redis-cluster-slave"
  template:
    metadata:
      labels:
        app: redis-cluster-slave
    spec:
      containers:
      - name: redis-cluster-slave
        args:
          - -c
          - cp /mnt/redis-slave.conf /data/ ; redis-server /data/redis-slave.conf
        command:
          - sh
        image: redis
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
            - name: rds-backport
              containerPort: 6379
              protocol: "TCP"
            # - name: cluster
            #   containerPort: 16379
            #   protocol: "TCP"
        volumeMounts:
          - mountPath: /mnt/
            readOnly: false
            name: redis-config-volume
          - mountPath: "/data/"
            name: "redis-slave-storage"
            readOnly: false
      volumes:
      - name: "redis-config-volume"
        configMap:
          name: "redis-cluster-config"
          items:
            - key: "redis-slave.conf"
              path: "redis-slave.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-slave-storage
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "redis-cluster-storage"
      resources:
        requests:
          storage: 3Gi
