apiVersion: v1
kind: Service
metadata:
  name: redis-master-svc
spec:
  type: NodePort
  ports:
   - port: 6379
     protocol: TCP
     targetPort: 6379
     name: mysql-svc
     nodePort: 31639
  selector:
    #app: mysql-0
     statefulset.kubernetes.io/pod-name: redis-cluster-master-0
