apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: redis-cluster-master-svc
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: redis-cluster-slave-svc
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
