apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume3
spec:
  storageClassName: redis-cluster-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/kubernetes/volums/redis-data/redis-cluster-3
    server: 10.25.96.30
