apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster-master
  labels:
    app: redis-cluster-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cluster-master
  #所属服务的DNS域名
  serviceName: "redis-cluster-master"
  template:
    metadata:
      labels:
        app: redis-cluster-master
    spec:
      containers:
      - name: redis-cluster-master
        args:
          - -c
          - cp /mnt/redis-master.conf /data/ ; redis-server /data/redis-master.conf
        command:
          - sh
        image: redis
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
            - name: rds-masterport
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 6379
              protocol: "TCP"
        volumeMounts:
          - mountPath: /mnt/
            readOnly: false
            name: redis-config-volume
          - mountPath: "/data/"
            name: "redis-master-storage"
            readOnly: false
      volumes:
      - name: "redis-config-volume"
        configMap:
          name: "redis-cluster-config"
          items:
            - key: "redis-master.conf"
              path: "redis-master.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-master-storage
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "redis-cluster-storage"
      resources:
        requests:
          storage: 3Gi
